### ISSUE TITLE
EGL lib issue

### ISSUE THREAD

**Issue by gilbertoyw** [naver/multi-hmr#23]
Hello, thanks for sharing this code. 

I've tried to run it on Windows 11 and Ubuntu 20.4, and I've got the same issue after executing the demo.py (see below). Can you help me?

(multihmr) PS C:\Users\gilbe\multi-hmr> python demo.py --img_folder example_data --out_folder demo_out --extra_views 1 --model_name multiHMR_896_L
Traceback (most recent call last):
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gilbe\multi-hmr\demo.py", line 19, in <module>
    from utils import normalize_rgb, render_meshes, get_focalLength_from_fieldOfView, demo_color as color, print_distance_on_image, render_side_views, create_scene, MEAN_PARAMS, CACHE_DIR_MULTIHMR, SMPLX_DIR
  File "C:\Users\gilbe\multi-hmr\utils\__init__.py", line 8, in <module>
    from .render import render_meshes, print_distance_on_image, render_side_views, create_scene, OPENCV_TO_OPENGL_CAMERA_CONVENTION
  File "C:\Users\gilbe\multi-hmr\utils\render.py", line 7, in <module>
    import pyrender
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\gilbe\anaconda3\envs\multihmr\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

**Comment by fabienbaradel** [comment]
Hi @gilbertoyw , thanks for your interest in our work.
It seems that your code is not able to load ```EGL``` library which is used for doing the rendering in our demo code.
Please have look to this [related issue](https://github.com/mkocabas/VIBE/issues/101).
In Ubuntu you need to install OpenGL using the following [command lines](https://github.com/mkocabas/VIBE/issues/101).
Hope it helps,

**Comment by gilbertoyw** [comment]
Thank you very much @fabienbaradel I will follow this thread.

**Comment by fabienbaradel** [comment]
Great, since it is not directly related to Multi-HMR I am closing this issue. Feel free to ask to re-open it.
Good luck!

**Comment by chris-hndz** [comment]
I only commented out line 6 and it worked for me on Windows:
# os.environ["PYOPENGL_PLATFORM"] = "egl"
