### ISSUE TITLE
Error when using `--extra_view 1` param in the demo.py

### ISSUE THREAD

**Issue by Kapi2910** [naver/multi-hmr#49]
I setup multihmr as per the README.md and when I run the following command:
```
python3.9 demo.py \
 --img_folder example_data \
 --out_folder demo_out \
  --extra_view 1 \
 --model_name multiHMR_896_L
```
I get the following error:

```
Traceback (most recent call last):
  File "/home/kapi-gpu/repos/multi-hmr/demo.py", line 231, in <module>
    pred_rend_array_bis, pred_rend_array_sideview, pred_rend_array_bev = render_side_views(img_array, _color, humans, model, K)
  File "/home/kapi-gpu/repos/multi-hmr/utils/render.py", line 426, in render_side_views
    pred_rend_array_bis = render_meshes(_bg* bg_array.copy(), l_verts, l_faces, 
  File "/home/kapi-gpu/repos/multi-hmr/utils/render.py", line 246, in render_meshes
    cone = pyvista.Cone(center=(0.0, 0.0, -height/2), direction=(0.0, 0.0, -1.0), height=height, radius=radius).extract_surface().triangulate()
  File "/home/kapi-gpu/miniconda3/envs/multihmr/lib/python3.9/site-packages/pyvista/core/filters/data_set.py", line 4761, in extract_surface
    return _get_output(surf_filter)
  File "/home/kapi-gpu/miniconda3/envs/multihmr/lib/python3.9/site-packages/pyvista/core/filters/__init__.py", line 48, in _get_output
    data.copy_meta_from(ido, deep=True)
  File "/home/kapi-gpu/miniconda3/envs/multihmr/lib/python3.9/site-packages/pyvista/core/dataset.py", line 1436, in copy_meta_from
    self._association_complex_names = deepcopy(ido._association_complex_names)
  File "/home/kapi-gpu/miniconda3/envs/multihmr/lib/python3.9/site-packages/pyvista/core/dataset.py", line 149, in __getattr__
```

Here is my system details.

```
OS: Ubuntu 20.04.6 LTS x86_64 
Kernel: 5.4.0-190-generic 
Shell: bash 5.0.17 
 CPU: Intel i5-6400 (4) @ 3.300GHz 
GPU: NVIDIA GeForce GTX 1070 
GPU: NVIDIA GeForce GTX 980 
```

Does any know what is up?
I'll be happy to answer anymore questions.

**Comment by fabienbaradel** [comment]
Hi @Kapi2910 ,
it seems that there a pyvista version compatibility issue.
Could you try to not add the ```cone``` in the rendering code snippet and see it solves the issue ?

**Comment by fabienbaradel** [comment]
@Bmodest found a way to solve this issue. I am closing it.
